/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/renderer/astryx-theme/picoTheme.ts
 * Command: npm run astryx:theme
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.1.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const picoTheme: DefinedTheme;
