import type { ITheme } from "@xterm/xterm";

// Boundary-core brand tokens mirrored by desktop renderer/styles.css.
export const color = {
  bg: "#ffffff",
  panel: "#f8f9fb",
  surface: "#f1f3f6",
  sidebar: "#f4f6f8",
  line: "#e3e7ed",
  lineStrong: "#c6cdd7",
  text: "#1b2432",
  muted: "#5f6977",
  faint: "#606d7e",
  accent: "#1b2432",
  accentStrong: "#2b3748",
  accentSoft: "#eef1f5",
  focus: "#1b2432",
  success: "#287342",
  successSoft: "#e7f1ea",
  warning: "#9b661d",
  warningSoft: "#f5ead6",
  danger: "#a34235",
  dangerSoft: "#f5e4e0",
};

export const terminalTheme = {
  background: color.bg,
  foreground: color.text,
  cursor: color.accent,
  cursorAccent: color.bg,
  selectionBackground: color.accentSoft,
  selectionInactiveBackground: color.surface,
  selectionForeground: color.text,
  black: color.text,
  red: color.danger,
  green: "#4c7a35",
  yellow: color.warning,
  // ANSI colors retain their meaning independently of the brand palette.
  blue: "#467bbd",
  magenta: "#8c5b9f",
  cyan: "#2c7a84",
  white: color.muted,
  brightBlack: color.faint,
  brightRed: "#c95546",
  brightGreen: "#628e45",
  brightYellow: "#b9812d",
  brightBlue: "#6093d2",
  brightMagenta: "#a570b7",
  brightCyan: "#48949d",
  brightWhite: color.text,
} satisfies ITheme;
