export const mobileTheme = {
  colors: {
    canvas: "#FFFFFF",
    surface: "#FAFAFA",
    surfaceMuted: "#F1F1EF",
    surfaceStrong: "#E8E8E5",
    sidebar: "#EEEEED",
    sidebarRaised: "#E6E6E4",
    ink: "#252522",
    inkSecondary: "#65645E",
    inkTertiary: "#73716B",
    line: "#E3E3E0",
    lineStrong: "#CCCCCA",
    accent: "#2F6E54",
    accentStrong: "#245741",
    accentSoft: "#E2EEE7",
    warning: "#9B661D",
    warningSoft: "#F5EAD6",
    danger: "#A34235",
    dangerSoft: "#F5E4E0",
    white: "#FFFFFF",
  },
  radius: {
    small: 7,
    medium: 11,
    large: 16,
    round: 999,
  },
  spacing: {
    xsmall: 4,
    small: 8,
    medium: 12,
    large: 16,
    xlarge: 24,
  },
  type: {
    caption: 11,
    small: 12,
    body: 14,
    title: 20,
  },
} as const;
