import type { ProviderProtocol } from "./model.js";

export interface ProviderPreset {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly category: "api" | "aggregator" | "plans" | "local" | "custom";
  readonly protocol: ProviderProtocol;
  readonly baseURL: string;
  /** Display only: account-specific templates must never become a saved URL. */
  readonly baseURLPlaceholder?: string;
  readonly apiKeyEnv: string;
  readonly auth?: "api-key" | "none";
  readonly models: readonly string[];
  readonly docs?: string;
  /** Basename of a vendored provider-brands SVG, without its extension. */
  readonly icon?: string;
}

// Compared with Maka's 60 registered provider types on 2026-09-06.
// Endpoint/auth facts are backed by each entry's first-party documentation.
// Models are a small editable starting list, never a promise of account access.
// Empty lists require a user-selected model; do not infer an entire live catalog.
// OpenCode routes by model protocol: keep Chat and Messages presets separate.
// Responses-only OpenCode models are intentionally absent from both lists.
export const providerPresets: readonly ProviderPreset[] = [
  {
    id: "opencode-free",
    name: "OpenCode Free",
    description: "无需 API Key 的免费模型；供应和额度以服务方为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://opencode.ai/zen/v1",
    apiKeyEnv: "OPENCODE_FREE_API_KEY",
    models: ["nemotron-3-ultra-free"],
    docs: "https://opencode.ai/docs/zen/",
    icon: "opencode",
    auth: "none",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go（Chat）",
    description: "Go 订阅 · GLM、Kimi、DeepSeek、MiMo 等 Chat 模型",
    category: "plans",
    protocol: "openai",
    baseURL: "https://opencode.ai/zen/go/v1",
    apiKeyEnv: "OPENCODE_GO_API_KEY",
    models: ["glm-5.2", "kimi-k2.6", "deepseek-v4-flash", "mimo-v2.5"],
    docs: "https://opencode.ai/docs/go/",
    icon: "opencode",
  },
  {
    id: "opencode-go-anthropic",
    name: "OpenCode Go（Messages）",
    description: "Go 订阅 · MiniMax、Qwen 的 Anthropic Messages 接口",
    category: "plans",
    protocol: "claude",
    baseURL: "https://opencode.ai/zen/go/v1",
    apiKeyEnv: "OPENCODE_GO_API_KEY",
    models: ["minimax-m3", "qwen3.7-plus"],
    docs: "https://opencode.ai/docs/go/",
    icon: "opencode",
  },
  {
    id: "opencode",
    name: "OpenCode Zen（Chat）",
    description: "按量付费 · DeepSeek、GLM、Kimi 等 Chat 模型",
    category: "plans",
    protocol: "openai",
    baseURL: "https://opencode.ai/zen/v1",
    apiKeyEnv: "OPENCODE_API_KEY",
    models: ["deepseek-v4-flash", "deepseek-v4-pro", "minimax-m3", "glm-5.2", "kimi-k2.6"],
    docs: "https://opencode.ai/docs/zen/",
    icon: "opencode",
  },
  {
    id: "opencode-anthropic",
    name: "OpenCode Zen（Messages）",
    description: "按量付费 · Claude、Qwen 的 Anthropic Messages 接口",
    category: "plans",
    protocol: "claude",
    baseURL: "https://opencode.ai/zen/v1",
    apiKeyEnv: "OPENCODE_API_KEY",
    models: ["claude-sonnet-5", "claude-opus-5", "qwen3.7-plus"],
    docs: "https://opencode.ai/docs/zen/",
    icon: "opencode",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.deepseek.com",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    models: ["deepseek-v4-flash", "deepseek-v4-pro"],
    docs: "https://api-docs.deepseek.com/",
    icon: "deepseek-color",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "claude",
    baseURL: "https://api.anthropic.com/v1",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    models: ["claude-sonnet-5", "claude-opus-5"],
    docs: "https://platform.claude.com/docs/en/models/overview",
    icon: "anthropic",
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
    models: ["gpt-4.1"],
    docs: "https://developers.openai.com/api/docs/models/gpt-4.1",
    icon: "openai",
  },
  {
    id: "google",
    name: "Google Gemini",
    description: "通过 Google 官方 OpenAI 兼容接口接入 Gemini",
    category: "api",
    protocol: "openai",
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
    apiKeyEnv: "GOOGLE_API_KEY",
    models: [],
    docs: "https://ai.google.dev/gemini-api/docs/openai",
    icon: "gemini",
  },
  {
    id: "kimi-coding-plan",
    name: "Kimi Coding Plan",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "claude",
    baseURL: "https://api.kimi.com/coding/v1",
    apiKeyEnv: "KIMI_CODING_PLAN_API_KEY",
    models: ["kimi-for-coding", "k3-256k", "k3"],
    docs: "https://www.kimi.com/code/docs/en/kimi-code/models.html",
    icon: "kimi",
  },
  {
    id: "minimax-coding-plan",
    name: "MiniMax Token Plan",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "claude",
    baseURL: "https://api.minimax.io/anthropic/v1",
    apiKeyEnv: "MINIMAX_CODING_PLAN_API_KEY",
    models: ["MiniMax-M3"],
    docs: "https://platform.minimax.io/docs/token-plan/intro",
    icon: "minimax",
  },
  {
    id: "tencent-coding-plan",
    name: "腾讯 Coding Plan",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://api.lkeap.cloud.tencent.com/coding/v3",
    apiKeyEnv: "TENCENT_CODING_PLAN_API_KEY",
    models: [],
    docs: "https://cloud.tencent.com/document/product/1823/130099",
    icon: "tencentcloud",
  },
  {
    id: "volcengine-coding-plan",
    name: "火山方舟 Coding Plan",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://ark.cn-beijing.volces.com/api/coding/v3",
    apiKeyEnv: "VOLCENGINE_CODING_PLAN_API_KEY",
    models: [],
    docs: "https://www.volcengine.com/docs/82379/1925114",
    icon: "volcengine",
  },
  {
    id: "tencent-token-plan",
    name: "腾讯 Token Plan",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://api.lkeap.cloud.tencent.com/plan/v3",
    apiKeyEnv: "TENCENT_TOKEN_PLAN_API_KEY",
    models: [],
    docs: "https://cloud.tencent.com/document/product/1823/130060",
    icon: "tencentcloud",
  },
  {
    id: "moonshot",
    name: "Moonshot / Kimi API",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.moonshot.cn/v1",
    apiKeyEnv: "MOONSHOT_API_KEY",
    models: [],
    docs: "https://www.kimi.com/code/docs/en/",
    icon: "moonshot",
  },
  {
    id: "zai-coding-plan",
    name: "Z.AI Coding Plan",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://api.z.ai/api/coding/paas/v4",
    apiKeyEnv: "ZAI_CODING_PLAN_API_KEY",
    models: [],
    docs: "https://docs.z.ai/api-reference/introduction",
    icon: "zai",
  },
  {
    id: "MiniMax",
    name: "MiniMax（国际站）",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "claude",
    baseURL: "https://api.minimax.io/anthropic/v1",
    apiKeyEnv: "MINIMAX_API_KEY",
    models: ["MiniMax-M3"],
    docs: "https://platform.minimax.io/docs/api-reference/text-anthropic-api",
    icon: "minimax",
  },
  {
    id: "MiniMax-cn",
    name: "MiniMax（中国站）",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "claude",
    baseURL: "https://api.minimax.cn/anthropic/v1",
    apiKeyEnv: "MINIMAX_CN_API_KEY",
    models: ["MiniMax-M3"],
    docs: "https://platform.minimaxi.com/docs/api-reference/text-anthropic-api",
    icon: "minimax",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow（国际站）",
    description: "通过一个 API Key 连接多家模型服务",
    category: "aggregator",
    protocol: "openai",
    baseURL: "https://api.siliconflow.com/v1",
    apiKeyEnv: "SILICONFLOW_API_KEY",
    models: [],
    docs: "https://docs.siliconflow.com/en/userguide/quickstart",
    icon: "siliconcloud",
  },
  {
    id: "vercel",
    name: "Vercel AI Gateway",
    description: "通过一个 API Key 连接多家模型服务",
    category: "aggregator",
    protocol: "openai",
    baseURL: "https://ai-gateway.vercel.sh/v1",
    apiKeyEnv: "VERCEL_API_KEY",
    models: [],
    docs: "https://vercel.com/docs/ai-gateway/sdks-and-apis/openai-chat-completions",
    icon: "vercel",
  },
  {
    id: "xai",
    name: "xAI",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.x.ai/v1",
    apiKeyEnv: "XAI_API_KEY",
    models: [],
    docs: "https://docs.x.ai/developers/rest-api-reference/inference/chat",
    icon: "xai",
  },
  {
    id: "zai",
    name: "Z.AI",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.z.ai/api/paas/v4",
    apiKeyEnv: "ZAI_API_KEY",
    models: [],
    docs: "https://docs.z.ai/api-reference/introduction",
    icon: "zai",
  },
  {
    id: "xiaomi",
    name: "小米 MiMo",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.xiaomimimo.com/v1",
    apiKeyEnv: "XIAOMI_API_KEY",
    models: [],
    docs: "https://mimo.mi.com/docs/en-US/tokenplan/integration/tools-overview",
    icon: "xiaomimimo",
  },
  {
    id: "xiaomi-token-plan-cn",
    name: "小米 Token Plan（中国）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://token-plan-cn.xiaomimimo.com/v1",
    apiKeyEnv: "XIAOMI_TOKEN_PLAN_CN_API_KEY",
    models: [],
    docs: "https://mimo.mi.com/docs/tokenplan/subscription",
    icon: "xiaomimimo",
  },
  {
    id: "xiaomi-token-plan-sgp",
    name: "小米 Token Plan（新加坡）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://token-plan-sgp.xiaomimimo.com/v1",
    apiKeyEnv: "XIAOMI_TOKEN_PLAN_SGP_API_KEY",
    models: [],
    docs: "https://mimo.mi.com/docs/tokenplan/subscription",
    icon: "xiaomimimo",
  },
  {
    id: "xiaomi-token-plan-ams",
    name: "小米 Token Plan（欧洲）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://token-plan-ams.xiaomimimo.com/v1",
    apiKeyEnv: "XIAOMI_TOKEN_PLAN_AMS_API_KEY",
    models: [],
    docs: "https://mimo.mi.com/docs/tokenplan/subscription",
    icon: "xiaomimimo",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.cerebras.ai/v1",
    apiKeyEnv: "CEREBRAS_API_KEY",
    models: ["qwen-3.8-27b"],
    docs: "https://inference-docs.cerebras.ai/resources/openai",
    icon: "cerebras",
  },
  {
    id: "mistral",
    name: "Mistral",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.mistral.ai/v1",
    apiKeyEnv: "MISTRAL_API_KEY",
    models: [],
    docs: "https://docs.mistral.ai/api/endpoint/chat",
    icon: "mistral",
  },
  {
    id: "cohere",
    name: "Cohere",
    description: "通过 Cohere 官方 OpenAI 兼容接口接入",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.cohere.ai/compatibility/v1",
    apiKeyEnv: "COHERE_API_KEY",
    models: ["command-a-plus-05-2026"],
    docs: "https://docs.cohere.com/docs/compatibility-api",
    icon: "cohere",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "通过一个 API Key 连接多家模型服务",
    category: "aggregator",
    protocol: "openai",
    baseURL: "https://router.huggingface.co/v1",
    apiKeyEnv: "HUGGINGFACE_API_KEY",
    models: [],
    docs: "https://huggingface.co/docs/inference-providers/tasks/chat-completion",
    icon: "huggingface",
  },
  {
    id: "zenmux",
    name: "ZenMux",
    description: "通过一个 API Key 连接多家模型服务",
    category: "aggregator",
    protocol: "openai",
    baseURL: "https://zenmux.ai/api/v1",
    apiKeyEnv: "ZENMUX_API_KEY",
    models: [],
    docs: "https://docs.zenmux.ai/api/openai/create-chat-completion",
    icon: "zenmux",
  },
  {
    id: "togetherai",
    name: "Together AI",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.together.ai/v1",
    apiKeyEnv: "TOGETHERAI_API_KEY",
    models: ["MiniMaxAI/MiniMax-M3"],
    docs: "https://docs.together.ai/docs/inference/openai-compatibility",
    icon: "together",
  },
  {
    id: "fireworks-ai",
    name: "Fireworks AI",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.fireworks.ai/inference/v1",
    apiKeyEnv: "FIREWORKS_AI_API_KEY",
    models: [],
    docs: "https://docs.fireworks.ai/tools-sdks/openai-compatibility",
    icon: "fireworks",
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://integrate.api.nvidia.com/v1",
    apiKeyEnv: "NVIDIA_API_KEY",
    models: [],
    docs: "https://docs.api.nvidia.com/nim/",
    icon: "nvidia",
  },
  {
    id: "tencent-tokenhub",
    name: "腾讯 TokenHub",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://tokenhub.tencentmaas.com/v1",
    apiKeyEnv: "TENCENT_TOKENHUB_API_KEY",
    models: [],
    docs: "https://cloud.tencent.com/document/product/1823/130079",
    icon: "tencentcloud",
  },
  {
    id: "stepfun",
    name: "阶跃星辰（中国）",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.stepfun.com/v1",
    apiKeyEnv: "STEPFUN_API_KEY",
    models: [],
    docs: "https://platform.stepfun.com/docs/zh/api-reference/chat/chat-completion-create",
    icon: "stepfun",
  },
  {
    id: "stepfun-step-plan",
    name: "Step Plan（中国）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://api.stepfun.com/step_plan/v1",
    apiKeyEnv: "STEPFUN_STEP_PLAN_API_KEY",
    models: ["step-3.5-flash"],
    docs: "https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api",
    icon: "stepfun",
  },
  {
    id: "stepfun-ai-step-plan",
    name: "Step Plan（国际）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://api.stepfun.ai/step_plan/v1",
    apiKeyEnv: "STEPFUN_AI_STEP_PLAN_API_KEY",
    models: ["step-3.7-flash"],
    docs: "https://platform.stepfun.ai/docs/en/step-plan/integrations/reasoning-api",
    icon: "stepfun",
  },
  {
    id: "stepfun-ai",
    name: "StepFun（国际）",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.stepfun.ai/v1",
    apiKeyEnv: "STEPFUN_AI_API_KEY",
    models: [],
    docs: "https://platform.stepfun.ai/docs/en/quickstart",
    icon: "stepfun",
  },
  {
    id: "volcengine-ark",
    name: "火山方舟 API",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyEnv: "VOLCENGINE_ARK_API_KEY",
    models: [],
    docs: "https://www.volcengine.com/docs/82379/1330626",
    icon: "volcengine",
  },
  {
    id: "deepinfra",
    name: "Deep Infra",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.deepinfra.com/v1/openai",
    apiKeyEnv: "DEEPINFRA_API_KEY",
    models: ["deepseek-ai/DeepSeek-V4-Flash-0731"],
    docs: "https://docs.deepinfra.com/chat/overview",
    icon: "deepinfra",
  },
  {
    id: "groq",
    name: "Groq",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://api.groq.com/openai/v1",
    apiKeyEnv: "GROQ_API_KEY",
    models: [],
    docs: "https://console.groq.com/docs/openai",
    icon: "groq",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    description: "通过一个 API Key 连接多家模型服务",
    category: "aggregator",
    protocol: "openai",
    baseURL: "https://openrouter.ai/api/v1",
    apiKeyEnv: "OPENROUTER_API_KEY",
    models: [],
    docs: "https://openrouter.ai/docs/quickstart",
    icon: "openrouter",
  },
  {
    id: "alibaba",
    name: "阿里云百炼（新加坡）",
    description: "填写控制台的新加坡业务空间地址，使用同地域 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "",
    apiKeyEnv: "ALIBABA_API_KEY",
    models: [],
    docs: "https://www.alibabacloud.com/help/en/model-studio/compatibility-of-openai-with-dashscope",
    icon: "alibabacloud",
    baseURLPlaceholder: "https://{WorkspaceId}.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
  },
  {
    id: "alibaba-cn",
    name: "阿里云百炼（中国）",
    description: "填写控制台的北京业务空间地址，使用同地域 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "",
    apiKeyEnv: "ALIBABA_CN_API_KEY",
    models: [],
    docs: "https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
    icon: "alibabacloud",
    baseURLPlaceholder: "https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
  },
  {
    id: "alibaba-coding-plan-cn",
    name: "阿里云 Coding Plan（中国）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://coding.dashscope.aliyuncs.com/v1",
    apiKeyEnv: "ALIBABA_CODING_PLAN_CN_API_KEY",
    models: [],
    docs: "https://help.aliyun.com/zh/model-studio/coding-plan",
    icon: "alibabacloud",
  },
  {
    id: "alibaba-coding-plan",
    name: "阿里云 Coding Plan（国际）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://coding-intl.dashscope.aliyuncs.com/v1",
    apiKeyEnv: "ALIBABA_CODING_PLAN_API_KEY",
    models: [],
    docs: "https://www.alibabacloud.com/help/en/model-studio/coding-plan",
    icon: "alibabacloud",
  },
  {
    id: "alibaba-token-plan-cn",
    name: "阿里云 Token Plan（中国）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    apiKeyEnv: "ALIBABA_TOKEN_PLAN_CN_API_KEY",
    models: [],
    docs: "https://help.aliyun.com/zh/model-studio/codex",
    icon: "alibabacloud",
  },
  {
    id: "alibaba-token-plan",
    name: "阿里云 Token Plan（新加坡）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    apiKeyEnv: "ALIBABA_TOKEN_PLAN_API_KEY",
    models: [],
    docs: "https://www.alibabacloud.com/help/en/model-studio/token-plan-overview",
    icon: "alibabacloud",
  },
  {
    id: "cloudflare-workers-ai",
    name: "Cloudflare Workers AI",
    description: "填写包含你本人 Account ID 的 Workers AI 地址",
    category: "api",
    protocol: "openai",
    baseURL: "",
    apiKeyEnv: "CLOUDFLARE_WORKERS_AI_API_KEY",
    models: [],
    docs: "https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/",
    icon: "cloudflare",
    baseURLPlaceholder: "https://api.cloudflare.com/client/v4/accounts/{AccountId}/ai/v1",
  },
  {
    id: "ollama-cloud",
    name: "Ollama Cloud",
    description: "Ollama 托管模型，使用云端 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://ollama.com/v1",
    apiKeyEnv: "OLLAMA_CLOUD_API_KEY",
    models: [],
    docs: "https://docs.ollama.com/cloud",
    icon: "ollama",
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "本机 Ollama 服务；填写已安装且支持工具调用的模型",
    category: "local",
    protocol: "openai",
    baseURL: "http://127.0.0.1:11434/v1",
    apiKeyEnv: "OLLAMA_API_KEY",
    models: [],
    docs: "https://docs.ollama.com/api/openai-compatibility",
    icon: "ollama",
    auth: "none",
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    description: "本机 LM Studio 服务；填写已加载的模型",
    category: "local",
    protocol: "openai",
    baseURL: "http://127.0.0.1:1234/v1",
    apiKeyEnv: "LM_STUDIO_API_KEY",
    models: [],
    docs: "https://lmstudio.ai/docs/developer/openai-compat",
    icon: "lmstudio",
    auth: "none",
  },
  {
    id: "localai",
    name: "LocalAI",
    description: "本地 OpenAI 兼容服务；启用服务端鉴权时选择 API Key",
    category: "local",
    protocol: "openai",
    baseURL: "http://127.0.0.1:8080/v1",
    apiKeyEnv: "LOCALAI_API_KEY",
    models: [],
    docs: "https://localai.io/docs/features/openai-functions/",
    auth: "none",
  },
  {
    id: "custom-openai",
    name: "自定义中转站（OpenAI Chat）",
    description: "连接兼容 OpenAI Chat Completions 的服务或网关",
    category: "custom",
    protocol: "openai",
    baseURL: "",
    apiKeyEnv: "OPENAI_API_KEY",
    models: [],
  },
  {
    id: "custom-anthropic",
    name: "自定义中转站（Anthropic）",
    description: "连接兼容 Anthropic Messages 的服务或网关",
    category: "custom",
    protocol: "claude",
    baseURL: "",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    models: [],
  },
  {
    id: "siliconflow-cn",
    name: "硅基流动（中国站）",
    description: "通过一个 API Key 连接多家模型服务",
    category: "aggregator",
    protocol: "openai",
    baseURL: "https://api.siliconflow.cn/v1",
    apiKeyEnv: "SILICONFLOW_CN_API_KEY",
    models: [],
    docs: "https://docs.siliconflow.cn/docs/userguide/quickstart",
    icon: "siliconcloud",
  },
  {
    id: "bigmodel",
    name: "智谱 BigModel（中国站）",
    description: "官方模型服务，使用对应站点的 API Key",
    category: "api",
    protocol: "openai",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyEnv: "BIGMODEL_API_KEY",
    models: ["glm-5.2"],
    docs: "https://docs.bigmodel.cn/cn/guide/develop/http/introduction",
    icon: "zai",
  },
  {
    id: "bigmodel-coding-plan",
    name: "智谱 GLM Coding Plan（中国站）",
    description: "使用套餐专属 Key；额度和可用模型以账户权益为准",
    category: "plans",
    protocol: "openai",
    baseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
    apiKeyEnv: "BIGMODEL_CODING_API_KEY",
    models: [],
    docs: "https://docs.bigmodel.cn/cn/coding-plan/tool/others",
    icon: "zai",
  },
];

export const unsupportedProviderPresets: readonly {
  readonly id: string;
  readonly name: string;
  readonly reason: string;
}[] = [
  {
    id: "volcengine-agent-plan",
    name: "Volcengine Ark Agent Plan (China)",
    reason: "需要 OpenAI Responses 协议；Pico 当前仅支持 Chat Completions 和 Anthropic Messages",
  },
  {
    id: "xai-oauth",
    name: "xAI OAuth (SuperGrok / X Premium)",
    reason: "需要专门的账号登录和令牌刷新流程；Pico 尚未实现",
  },
  {
    id: "openai-responses-compatible",
    name: "Custom relay (OpenAI Responses)",
    reason: "需要 OpenAI Responses 协议；Pico 当前仅支持 Chat Completions 和 Anthropic Messages",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    reason: "需要专门的账号登录和令牌刷新流程；Pico 尚未实现",
  },
  {
    id: "claude-subscription",
    name: "Claude Subscription (Pro / Max OAuth)",
    reason: "Maka 已停用此订阅连接；不能使用订阅凭证代替 Anthropic API Key",
  },
  {
    id: "openai-codex",
    name: "OpenAI OAuth (ChatGPT / Codex)",
    reason: "需要专门的账号登录和令牌刷新流程；Pico 尚未实现",
  },
];

export function nextProviderId(base: string, existingIds: readonly string[]): string {
  const used = new Set(existingIds);
  if (!used.has(base)) return base;
  let suffix = 2;
  while (used.has(`${base}-${suffix}`)) suffix += 1;
  return `${base}-${suffix}`;
}
